// create principals and roles
USE ROLE SECURITYADMIN;

CREATE USER IF NOT EXISTS 
  FIVETRAN_SERVICE_ACCOUNT
  PASSWORD = 'my cool password here' // use your own password, dummy 
  MUST_CHANGE_PASSWORD = FALSE;

CREATE ROLE IF NOT EXISTS FIVETRAN_READ_ROLE;
CREATE ROLE IF NOT EXISTS FIVETRAN_ADMIN_ROLE;


//  Assign roles
GRANT ROLE FIVETRAN_READ_ROLE      TO ROLE SYSADMIN;
GRANT ROLE FIVETRAN_ADMIN_ROLE     TO ROLE SYSADMIN;
GRANT ROLE FIVETRAN_READ_ROLE      TO ROLE RTE;
GRANT ROLE FIVETRAN_READ_ROLE      TO ROLE HASHMAP_TRAINING_USER;
GRANT ROLE ACCOUNT_USAGE_READ_ROLE TO ROLE FIVETRAN_ADMIN_ROLE;
GRANT ROLE FIVETRAN_READ_ROLE      TO ROLE FIVETRAN_ADMIN_ROLE;
GRANT ROLE FIVETRAN_READ_ROLE      TO ROLE SNOWALERT;
GRANT ROLE FIVETRAN_ADMIN_ROLE     TO USER FIVETRAN_SERVICE_ACCOUNT;
GRANT ROLE SYSADMIN                TO USER FIVETRAN_SERVICE_ACCOUNT;


// CREATE TOP LEVEL OBJECTS
USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS 
  FIVETRAN_DB 
  COMMENT='Database for Fivetran ingestion.';
  
CREATE WAREHOUSE IF NOT EXISTS
  FIVETRAN_INGESTION_WH
  COMMENT='Warehouse for data ingestion from Fivetran'
  WAREHOUSE_SIZE=XSMALL
  AUTO_SUSPEND=60
  INITIALLY_SUSPENDED=TRUE;


// transfer ownerships
USE ROLE SYSADMIN;
GRANT OWNERSHIP ON DATABASE FIVETRAN_DB TO ROLE FIVETRAN_ADMIN_ROLE;
GRANT OWNERSHIP ON WAREHOUSE FIVETRAN_INGESTION_WH TO ROLE FIVETRAN_ADMIN_ROLE;


// set service account defaults
USE ROLE SECURITYADMIN;
ALTER USER 
  FIVETRAN_SERVICE_ACCOUNT 
SET 
  DEFAULT_ROLE=FIVETRAN_ADMIN_ROLE
  DEFAULT_WAREHOUSE=FIVETRAN_INGESTION_WH;


// grant read permissions to fivetran ingestion data
USE ROLE SECURITYADMIN;
GRANT USAGE ON DATABASE FIVETRAN_DB TO ROLE FIVETRAN_READ_ROLE;
GRANT USAGE ON SCHEMA FIVETRAN_DB.SALESFORCE TO ROLE FIVETRAN_READ_ROLE;
GRANT USAGE ON SCHEMA FIVETRAN_DB.FIVETRAN_OASIS_ANCESTRAL_STAGING TO ROLE FIVETRAN_READ_ROLE;
GRANT USAGE ON SCHEMA FIVETRAN_DB.PUBLIC TO ROLE FIVETRAN_READ_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA FIVETRAN_DB.SALESFORCE TO ROLE FIVETRAN_READ_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA FIVETRAN_DB.SALESFORCE TO ROLE FIVETRAN_READ_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FIVETRAN_DB.SALESFORCE TO ROLE FIVETRAN_READ_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA FIVETRAN_DB.SALESFORCE TO ROLE FIVETRAN_READ_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA FIVETRAN_DB.FIVETRAN_OASIS_ANCESTRAL_STAGING TO ROLE FIVETRAN_READ_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA FIVETRAN_DB.FIVETRAN_OASIS_ANCESTRAL_STAGING TO ROLE FIVETRAN_READ_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FIVETRAN_DB.FIVETRAN_OASIS_ANCESTRAL_STAGING TO ROLE FIVETRAN_READ_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA FIVETRAN_DB.FIVETRAN_OASIS_ANCESTRAL_STAGING TO ROLE FIVETRAN_READ_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA FIVETRAN_DB.PUBLIC TO ROLE FIVETRAN_READ_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA FIVETRAN_DB.PUBLIC TO ROLE FIVETRAN_READ_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FIVETRAN_DB.PUBLIC TO ROLE FIVETRAN_READ_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA FIVETRAN_DB.PUBLIC TO ROLE FIVETRAN_READ_ROLE;

// ADD GITHUB READ ACCESS
USE ROLE SECURITYADMIN;
GRANT USAGE ON SCHEMA FIVETRAN_DB.GITHUB                   TO ROLE FIVETRAN_READ_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA FIVETRAN_DB.GITHUB    TO ROLE FIVETRAN_READ_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA FIVETRAN_DB.GITHUB     TO ROLE FIVETRAN_READ_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FIVETRAN_DB.GITHUB TO ROLE FIVETRAN_READ_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA FIVETRAN_DB.GITHUB  TO ROLE FIVETRAN_READ_ROLE;

// ADD SNOWWATCH READ ACCESS
USE ROLE SECURITYADMIN;
GRANT USAGE ON SCHEMA FIVETRAN_DB.SNOWWATCH_HASHMAP_AWS_EC2                   TO ROLE FIVETRAN_READ_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA FIVETRAN_DB.SNOWWATCH_HASHMAP_AWS_EC2    TO ROLE FIVETRAN_READ_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA FIVETRAN_DB.SNOWWATCH_HASHMAP_AWS_EC2     TO ROLE FIVETRAN_READ_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FIVETRAN_DB.SNOWWATCH_HASHMAP_AWS_EC2 TO ROLE FIVETRAN_READ_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA FIVETRAN_DB.SNOWWATCH_HASHMAP_AWS_EC2  TO ROLE FIVETRAN_READ_ROLE;
GRANT USAGE ON SCHEMA FIVETRAN_DB.SNOWWATCH_HASHMAP_AWS_ELB                   TO ROLE FIVETRAN_READ_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA FIVETRAN_DB.SNOWWATCH_HASHMAP_AWS_ELB    TO ROLE FIVETRAN_READ_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA FIVETRAN_DB.SNOWWATCH_HASHMAP_AWS_ELB     TO ROLE FIVETRAN_READ_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FIVETRAN_DB.SNOWWATCH_HASHMAP_AWS_ELB TO ROLE FIVETRAN_READ_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA FIVETRAN_DB.SNOWWATCH_HASHMAP_AWS_ELB  TO ROLE FIVETRAN_READ_ROLE;
GRANT USAGE ON SCHEMA FIVETRAN_DB.SNOWWATCH_HASHMAP_AWS_IAM                   TO ROLE FIVETRAN_READ_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA FIVETRAN_DB.SNOWWATCH_HASHMAP_AWS_IAM    TO ROLE FIVETRAN_READ_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA FIVETRAN_DB.SNOWWATCH_HASHMAP_AWS_IAM     TO ROLE FIVETRAN_READ_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FIVETRAN_DB.SNOWWATCH_HASHMAP_AWS_IAM TO ROLE FIVETRAN_READ_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA FIVETRAN_DB.SNOWWATCH_HASHMAP_AWS_IAM  TO ROLE FIVETRAN_READ_ROLE;
GRANT USAGE ON SCHEMA FIVETRAN_DB.SNOWWATCH_HASHMAP_AWS_SECURITY_GROUPS                   TO ROLE FIVETRAN_READ_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA FIVETRAN_DB.SNOWWATCH_HASHMAP_AWS_SECURITY_GROUPS    TO ROLE FIVETRAN_READ_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA FIVETRAN_DB.SNOWWATCH_HASHMAP_AWS_SECURITY_GROUPS     TO ROLE FIVETRAN_READ_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FIVETRAN_DB.SNOWWATCH_HASHMAP_AWS_SECURITY_GROUPS TO ROLE FIVETRAN_READ_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA FIVETRAN_DB.SNOWWATCH_HASHMAP_AWS_SECURITY_GROUPS  TO ROLE FIVETRAN_READ_ROLE;

// add hashmap_snowflake_usage read access
USE ROLE SECURITYADMIN;
GRANT USAGE ON SCHEMA FIVETRAN_DB.HASHMAP_SNOWFLAKE_USAGE                   TO ROLE FIVETRAN_READ_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA FIVETRAN_DB.HASHMAP_SNOWFLAKE_USAGE    TO ROLE FIVETRAN_READ_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA FIVETRAN_DB.HASHMAP_SNOWFLAKE_USAGE     TO ROLE FIVETRAN_READ_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FIVETRAN_DB.HASHMAP_SNOWFLAKE_USAGE TO ROLE FIVETRAN_READ_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA FIVETRAN_DB.HASHMAP_SNOWFLAKE_USAGE  TO ROLE FIVETRAN_READ_ROLE;

// add aws usage and cost read access
USE ROLE SECURITYADMIN;
GRANT USAGE ON SCHEMA FIVETRAN_DB.HASHMAP_AWS_COST_MONITORING                   TO ROLE FIVETRAN_READ_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA FIVETRAN_DB.HASHMAP_AWS_COST_MONITORING    TO ROLE FIVETRAN_READ_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA FIVETRAN_DB.HASHMAP_AWS_COST_MONITORING     TO ROLE FIVETRAN_READ_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FIVETRAN_DB.HASHMAP_AWS_COST_MONITORING TO ROLE FIVETRAN_READ_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA FIVETRAN_DB.HASHMAP_AWS_COST_MONITORING  TO ROLE FIVETRAN_READ_ROLE;

// add azure usage and cost read access
USE ROLE SECURITYADMIN;
GRANT USAGE ON SCHEMA FIVETRAN_DB.HASHMAP_AZURE_COST_MONITORING                   TO ROLE FIVETRAN_READ_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA FIVETRAN_DB.HASHMAP_AZURE_COST_MONITORING    TO ROLE FIVETRAN_READ_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA FIVETRAN_DB.HASHMAP_AZURE_COST_MONITORING     TO ROLE FIVETRAN_READ_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FIVETRAN_DB.HASHMAP_AZURE_COST_MONITORING TO ROLE FIVETRAN_READ_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA FIVETRAN_DB.HASHMAP_AZURE_COST_MONITORING  TO ROLE FIVETRAN_READ_ROLE;
