//===========================================================
// delete all snowalert objects in Snowflake
//===========================================================
// database
USE ROLE SYSADMIN;
DROP DATABASE SNOWALERT;

// warehouses
USE ROLE SYSADMIN;
DROP WAREHOUSE SNOWALERT;
DROP WAREHOUSE EXCEL_SNOWALERT_WH;
DROP WAREHOUSE METABASE_SNOWALERT_WH;
DROP WAREHOUSE POWERBI_SNOWALERT_WH;
DROP WAREHOUSE SIGMA_SNOWALERT_WH;
DROP WAREHOUSE TABLEAU_SNOWALERT_WH;

// roles
USE ROLE SECURITYADMIN;
DROP ROLE SNOWALERT;
DROP ROLE SNOWALERT_BI_READ_ROLE;
DROP ROLE EXCEL_ADMIN_ROLE;
DROP ROLE EXCEL_SNOWALERT_USER_ROLE;
DROP ROLE METABASE_ADMIN_ROLE;
DROP ROLE METABASE_SNOWALERT_USER_ROLE;
DROP ROLE POWERBI_ADMIN_ROLE;
DROP ROLE POWERBI_SNOWALERT_USER_ROLE;
DROP ROLE SIGMA_ADMIN_ROLE;
DROP ROLE SIGMA_SNOWALERT_USER_ROLE;
DROP ROLE TABLEAU_ADMIN_ROLE;
DROP ROLE TABLEAU_SNOWALERT_USER_ROLE;

// users
USE ROLE SECURITYADMIN;
DROP USER EXCEL_SNOWALERT_SERVICE_ACCOUNT
DROP USER METABASE_SNOWALERT_SERVICE_ACCOUNT;
DROP USER POWERBI_SNOWALERT_SERVICE_ACCOUNT;
DROP USER SIGMA_SNOWALERT_SERVICE_ACCOUNT;
DROP USER TABLEAU_SNOWALERT_SERVICE_ACCOUNT;
//===========================================================