//===========================================================
// Create BI views of snowalert data
//===========================================================
USE ROLE SNOWALERT;
USE WAREHOUSE SNOWALERT;

CREATE SCHEMA IF NOT EXISTS SNOWALERT.BI;



// AWS views
// passthrough view for cloudtrail 
CREATE OR REPLACE VIEW
  SNOWALERT.BI.CLOUDTRAIL
AS (
  SELECT * FROM SNOWALERT.AWS.CLOUDTRAIL_FLATTENED
);

// Create current users view
CREATE OR REPLACE VIEW
  SNOWALERT.BI.CURRENT_IAM_USERS
AS (
  SELECT
    *
  FROM
    SNOWALERT.AWS.IAM_USER_MONITORING_LANDING_ZONE
  WHERE
    MONITORED_TIME = (
      SELECT 
        MAX(MONITORED_TIME) 
      FROM 
        SNOWALERT.AWS.IAM_USER_MONITORING_LANDING_ZONE
    )
);

// Create current human users view
CREATE OR REPLACE VIEW
  SNOWALERT.BI.CURRENT_IAM_HUMAN_USERS
AS (
  SELECT
    *
  FROM
    SNOWALERT.BI.CURRENT_IAM_USERS
  WHERE
    USER_NAME NOT IN (
        'Jenkins',
        'TravisUploader'
    )
);

// Create current security group view
CREATE OR REPLACE VIEW
  SNOWALERT.BI.CURRENT_SECURITY_GROUPS
AS (
  SELECT
    *
  FROM
    SNOWALERT.AWS.SECURITY_GROUP_MONITORING_LANDING_ZONE
  WHERE
    MONITORED_TIME = (
      SELECT 
        MAX(MONITORED_TIME) 
      FROM 
        SNOWALERT.AWS.SECURITY_GROUP_MONITORING_LANDING_ZONE
    )
);



// Snowalert alert/violation views
// passthrough view for alerts
CREATE OR REPLACE VIEW
  SNOWALERT.BI.ALERTS
AS (
  SELECT * FROM SNOWALERT.DATA.ALERTS
);

// passthrough view for violations
CREATE OR REPLACE VIEW
  SNOWALERT.BI.VIOLATIONS
AS (
  SELECT * FROM SNOWALERT.DATA.VIOLATIONS
);



// Snowflake monitoring data from Fivetran
// passthrough view for warehouse usage
CREATE OR REPLACE VIEW
  SNOWALERT.BI.WAREHOUSE_METERING_HISTORY
AS (
  SELECT * FROM FIVETRAN_DB.HASHMAP_SNOWFLAKE_USAGE.WAREHOUSE_METERING_HISTORY
);

// view for snowpipes
CREATE OR REPLACE VIEW
  SNOWALERT.BI.SNOWPIPES
AS (
  SELECT 
    *,
    (SELECT MAX(INGESTION_TIME) FROM FIVETRAN_DB.HASHMAP_SNOWFLAKE_USAGE.SNOWPIPES) AS LATEST_INGESTION_TIME,
    INGESTION_TIME = LATEST_INGESTION_TIME AS IS_LATEST
  FROM FIVETRAN_DB.HASHMAP_SNOWFLAKE_USAGE.SNOWPIPES
);

// passthrough view for snowpipe usage history
CREATE OR REPLACE VIEW
  SNOWALERT.BI.SNOWPIPE_USAGE_HISTORY
AS (
  SELECT * FROM FIVETRAN_DB.HASHMAP_SNOWFLAKE_USAGE.SNOWPIPE_USAGE_HISTORY
);

// passthrough view for query history
CREATE OR REPLACE VIEW
  SNOWALERT.BI.QUERY_HISTORY
AS (
  SELECT * FROM FIVETRAN_DB.HASHMAP_SNOWFLAKE_USAGE.QUERY_HISTORY
);

// view for tasks
CREATE OR REPLACE VIEW
  SNOWALERT.BI.TASKS
AS (
  SELECT 
    *,
    (SELECT MAX(INGESTION_TIME) FROM FIVETRAN_DB.HASHMAP_SNOWFLAKE_USAGE.TASKS) AS LATEST_INGESTION_TIME,
    INGESTION_TIME = LATEST_INGESTION_TIME AS IS_LATEST
  FROM FIVETRAN_DB.HASHMAP_SNOWFLAKE_USAGE.TASKS
);

// passthrough view for task usage history
CREATE OR REPLACE VIEW
  SNOWALERT.BI.TASK_USAGE_HISTORY
AS (
  SELECT * FROM FIVETRAN_DB.HASHMAP_SNOWFLAKE_USAGE.TASK_USAGE_HISTORY
);

// passthrough view for aws cost monitoring
CREATE OR REPLACE VIEW
  SNOWALERT.BI.HASHMAP_AWS_COSTS
AS (
  SELECT * FROM FIVETRAN_DB.HASHMAP_AWS_COST_MONITORING.HASHMAP_AWS_COSTS
);

// passthrough view for azure cost monitoring
CREATE OR REPLACE VIEW
  SNOWALERT.BI.HASHMAP_AZURE_COSTS
AS (
  SELECT * FROM FIVETRAN_DB.HASHMAP_AZURE_COST_MONITORING.HASHMAP_AZURE_COSTS
);
//===========================================================