//===========================================================
// Create role structure for read access to snowalert
// BI data.
//===========================================================
// create role
USE ROLE SECURITYADMIN;
CREATE ROLE IF NOT EXISTS SNOWALERT_BI_READ_ROLE;

// permission role
USE ROLE SECURITYADMIN;
GRANT USAGE ON DATABASE SNOWALERT TO ROLE SNOWALERT_BI_READ_ROLE;
GRANT USAGE ON SCHEMA SNOWALERT.BI TO ROLE SNOWALERT_BI_READ_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA SNOWALERT.BI TO ROLE SNOWALERT_BI_READ_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA SNOWALERT.BI TO ROLE SNOWALERT_BI_READ_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA SNOWALERT.BI TO ROLE SNOWALERT_BI_READ_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SNOWALERT.BI TO ROLE SNOWALERT_BI_READ_ROLE;
GRANT SELECT ON ALL MATERIALIZED VIEWS IN SCHEMA SNOWALERT.BI TO ROLE SNOWALERT_BI_READ_ROLE;
GRANT SELECT ON FUTURE MATERIALIZED VIEWS IN SCHEMA SNOWALERT.BI TO ROLE SNOWALERT_BI_READ_ROLE;
//===========================================================